/********************************************************************************
** Form generated from reading UI file 'QtGuiApplication.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QTGUIAPPLICATION_H
#define UI_QTGUIAPPLICATION_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_QtGuiApplicationClass
{
public:
    QWidget *centralWidget;
    QTabWidget *tabwidgt;
    QWidget *tab;
    QPushButton *btn_ok;
    QGroupBox *groupBox;
    QGroupBox *groupBox_4;
    QComboBox *cm_task_3;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLineEdit *lineEdit_11;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QComboBox *cm_type_3;
    QLabel *label_44;
    QLineEdit *lineEdit_12;
    QLineEdit *platform_name_3;
    QLineEdit *linecode_4;
    QComboBox *cm_role_3;
    QPushButton *btn_create_3;
    QPushButton *PLAT_DELETE;
    QGroupBox *groupBox_2;
    QComboBox *cm_data1_3;
    QLabel *label_34;
    QPushButton *data_3;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QPushButton *btn_create;
    QComboBox *cm_plat;
    QLabel *label_17;
    QListWidget *listWidget;
    QPushButton *pushButton;
    QTreeWidget *treeWidget;
    QPushButton *btn_zip;
    QGroupBox *groupBox_3;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *linetime;
    QLineEdit *linestime;
    QLabel *label_6;
    QLineEdit *linecode;
    QLineEdit *linedescrip;
    QLabel *label;
    QPushButton *btn_save;
    QLabel *label_3;
    QLineEdit *linename;
    QLineEdit *linetime_3;
    QPushButton *btn_create_2;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *lineato;
    QLineEdit *linetime_2;
    QPushButton *btn_open;
    QLabel *label_2;
    QWidget *tab_2;
    QGroupBox *groupBox_21;
    QPushButton *Rbtn_new;
    QLineEdit *REditOperator;
    QLabel *label_9;
    QLineEdit *REditCode;
    QLineEdit *REditSTime;
    QLineEdit *REditDescrip;
    QLineEdit *REditETime;
    QLabel *label_12;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QPushButton *Rbtn_open;
    QPushButton *btn_modify;
    QLineEdit *REditLibID_4;
    QLabel *label_46;
    QLabel *label_48;
    QLineEdit *REditLibID_5;
    QLineEdit *REditName_2;
    QLabel *label_18;
    QGroupBox *groupBox_41;
    QLineEdit *REditcode;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *REditFacName;
    QLabel *label_28;
    QLineEdit *REditLibID;
    QLabel *label_29;
    QLineEdit *REditLibVersion;
    QLabel *label_30;
    QGroupBox *groupBox_5;
    QLabel *label_35;
    QComboBox *Rcm_data;
    QLabel *label_45;
    QListWidget *RListData;
    QPushButton *btn_add;
    QPushButton *btn_delete;
    QLabel *label_47;
    QLineEdit *REditLibID_2;
    QLineEdit *REditLibID_3;
    QPushButton *btn_modify_2;
    QComboBox *comboBox;
    QComboBox *cm_equipment;
    QLabel *label_31;
    QPushButton *btn_modify_3;
    QPushButton *delete_equip;
    QTreeWidget *RTree;
    QPushButton *btn_zip_2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *QtGuiApplicationClass)
    {
        if (QtGuiApplicationClass->objectName().isEmpty())
            QtGuiApplicationClass->setObjectName(QString::fromUtf8("QtGuiApplicationClass"));
        QtGuiApplicationClass->resize(983, 661);
        centralWidget = new QWidget(QtGuiApplicationClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabwidgt = new QTabWidget(centralWidget);
        tabwidgt->setObjectName(QString::fromUtf8("tabwidgt"));
        tabwidgt->setGeometry(QRect(20, 10, 901, 601));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        btn_ok = new QPushButton(tab);
        btn_ok->setObjectName(QString::fromUtf8("btn_ok"));
        btn_ok->setGeometry(QRect(810, 540, 71, 21));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 180, 521, 391));
        groupBox_4 = new QGroupBox(groupBox);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 20, 501, 111));
        cm_task_3 = new QComboBox(groupBox_4);
        cm_task_3->setObjectName(QString::fromUtf8("cm_task_3"));
        cm_task_3->setGeometry(QRect(432, 59, 69, 18));
        label_38 = new QLabel(groupBox_4);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 59, 66, 16));
        label_39 = new QLabel(groupBox_4);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 10, 30, 16));
        label_40 = new QLabel(groupBox_4);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(342, 10, 78, 16));
        lineEdit_11 = new QLineEdit(groupBox_4);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(106, 83, 230, 18));
        lineEdit_11->setMaximumSize(QSize(16777215, 20));
        label_41 = new QLabel(groupBox_4);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(342, 35, 78, 16));
        label_42 = new QLabel(groupBox_4);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(342, 59, 72, 16));
        label_43 = new QLabel(groupBox_4);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 83, 90, 16));
        cm_type_3 = new QComboBox(groupBox_4);
        cm_type_3->setObjectName(QString::fromUtf8("cm_type_3"));
        cm_type_3->setGeometry(QRect(432, 10, 69, 19));
        label_44 = new QLabel(groupBox_4);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 35, 78, 16));
        lineEdit_12 = new QLineEdit(groupBox_4);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(106, 59, 230, 18));
        platform_name_3 = new QLineEdit(groupBox_4);
        platform_name_3->setObjectName(QString::fromUtf8("platform_name_3"));
        platform_name_3->setGeometry(QRect(106, 35, 230, 18));
        linecode_4 = new QLineEdit(groupBox_4);
        linecode_4->setObjectName(QString::fromUtf8("linecode_4"));
        linecode_4->setGeometry(QRect(106, 10, 230, 19));
        cm_role_3 = new QComboBox(groupBox_4);
        cm_role_3->setObjectName(QString::fromUtf8("cm_role_3"));
        cm_role_3->setGeometry(QRect(432, 35, 69, 18));
        btn_create_3 = new QPushButton(groupBox_4);
        btn_create_3->setObjectName(QString::fromUtf8("btn_create_3"));
        btn_create_3->setGeometry(QRect(340, 80, 81, 21));
        PLAT_DELETE = new QPushButton(groupBox_4);
        PLAT_DELETE->setObjectName(QString::fromUtf8("PLAT_DELETE"));
        PLAT_DELETE->setGeometry(QRect(420, 80, 75, 23));
        groupBox_2 = new QGroupBox(groupBox);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 140, 511, 241));
        cm_data1_3 = new QComboBox(groupBox_2);
        cm_data1_3->setObjectName(QString::fromUtf8("cm_data1_3"));
        cm_data1_3->setGeometry(QRect(56, 10, 69, 20));
        label_34 = new QLabel(groupBox_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(20, 10, 30, 16));
        data_3 = new QPushButton(groupBox_2);
        data_3->setObjectName(QString::fromUtf8("data_3"));
        data_3->setGeometry(QRect(250, 40, 61, 21));
        label_36 = new QLabel(groupBox_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(140, 10, 54, 12));
        label_37 = new QLabel(groupBox_2);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(340, 10, 21, 16));
        lineEdit_9 = new QLineEdit(groupBox_2);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(200, 10, 113, 20));
        lineEdit_10 = new QLineEdit(groupBox_2);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(370, 10, 113, 20));
        btn_create = new QPushButton(groupBox_2);
        btn_create->setObjectName(QString::fromUtf8("btn_create"));
        btn_create->setGeometry(QRect(320, 40, 61, 21));
        cm_plat = new QComboBox(groupBox_2);
        cm_plat->setObjectName(QString::fromUtf8("cm_plat"));
        cm_plat->setGeometry(QRect(90, 40, 69, 22));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 40, 71, 20));
        listWidget = new QListWidget(groupBox_2);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(10, 70, 491, 161));
        pushButton = new QPushButton(groupBox_2);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(390, 40, 61, 23));
        treeWidget = new QTreeWidget(tab);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem();
        __qtreewidgetitem->setText(0, QString::fromUtf8("1"));
        treeWidget->setHeaderItem(__qtreewidgetitem);
        treeWidget->setObjectName(QString::fromUtf8("treeWidget"));
        treeWidget->setGeometry(QRect(530, 10, 361, 511));
        btn_zip = new QPushButton(tab);
        btn_zip->setObjectName(QString::fromUtf8("btn_zip"));
        btn_zip->setGeometry(QRect(710, 540, 71, 21));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 0, 511, 181));
        label_4 = new QLabel(groupBox_3);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 90, 75, 20));
        label_5 = new QLabel(groupBox_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 118, 75, 20));
        linetime = new QLineEdit(groupBox_3);
        linetime->setObjectName(QString::fromUtf8("linetime"));
        linetime->setGeometry(QRect(91, 118, 141, 20));
        linetime->setMaximumSize(QSize(16777215, 20));
        linestime = new QLineEdit(groupBox_3);
        linestime->setObjectName(QString::fromUtf8("linestime"));
        linestime->setGeometry(QRect(90, 88, 141, 20));
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 48, 75, 20));
        linecode = new QLineEdit(groupBox_3);
        linecode->setObjectName(QString::fromUtf8("linecode"));
        linecode->setGeometry(QRect(90, 8, 141, 20));
        linedescrip = new QLineEdit(groupBox_3);
        linedescrip->setObjectName(QString::fromUtf8("linedescrip"));
        linedescrip->setGeometry(QRect(91, 48, 141, 20));
        label = new QLabel(groupBox_3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(9, 8, 75, 20));
        btn_save = new QPushButton(groupBox_3);
        btn_save->setObjectName(QString::fromUtf8("btn_save"));
        btn_save->setGeometry(QRect(410, 150, 41, 21));
        label_3 = new QLabel(groupBox_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(280, 50, 75, 20));
        linename = new QLineEdit(groupBox_3);
        linename->setObjectName(QString::fromUtf8("linename"));
        linename->setGeometry(QRect(360, 10, 141, 20));
        linetime_3 = new QLineEdit(groupBox_3);
        linetime_3->setObjectName(QString::fromUtf8("linetime_3"));
        linetime_3->setGeometry(QRect(360, 120, 141, 20));
        linetime_3->setMaximumSize(QSize(16777215, 20));
        btn_create_2 = new QPushButton(groupBox_3);
        btn_create_2->setObjectName(QString::fromUtf8("btn_create_2"));
        btn_create_2->setGeometry(QRect(350, 150, 61, 21));
        label_7 = new QLabel(groupBox_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(279, 90, 75, 20));
        label_8 = new QLabel(groupBox_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(279, 120, 75, 20));
        lineato = new QLineEdit(groupBox_3);
        lineato->setObjectName(QString::fromUtf8("lineato"));
        lineato->setGeometry(QRect(361, 50, 141, 20));
        linetime_2 = new QLineEdit(groupBox_3);
        linetime_2->setObjectName(QString::fromUtf8("linetime_2"));
        linetime_2->setGeometry(QRect(360, 90, 141, 20));
        linetime_2->setMaximumSize(QSize(16777215, 20));
        btn_open = new QPushButton(groupBox_3);
        btn_open->setObjectName(QString::fromUtf8("btn_open"));
        btn_open->setGeometry(QRect(310, 150, 41, 21));
        label_2 = new QLabel(groupBox_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(279, 10, 75, 20));
        tabwidgt->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        groupBox_21 = new QGroupBox(tab_2);
        groupBox_21->setObjectName(QString::fromUtf8("groupBox_21"));
        groupBox_21->setGeometry(QRect(10, 10, 511, 151));
        Rbtn_new = new QPushButton(groupBox_21);
        Rbtn_new->setObjectName(QString::fromUtf8("Rbtn_new"));
        Rbtn_new->setGeometry(QRect(360, 120, 61, 23));
        REditOperator = new QLineEdit(groupBox_21);
        REditOperator->setObjectName(QString::fromUtf8("REditOperator"));
        REditOperator->setGeometry(QRect(91, 70, 141, 20));
        label_9 = new QLabel(groupBox_21);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 100, 75, 20));
        REditCode = new QLineEdit(groupBox_21);
        REditCode->setObjectName(QString::fromUtf8("REditCode"));
        REditCode->setGeometry(QRect(91, 20, 141, 20));
        REditSTime = new QLineEdit(groupBox_21);
        REditSTime->setObjectName(QString::fromUtf8("REditSTime"));
        REditSTime->setGeometry(QRect(91, 100, 141, 20));
        REditDescrip = new QLineEdit(groupBox_21);
        REditDescrip->setObjectName(QString::fromUtf8("REditDescrip"));
        REditDescrip->setGeometry(QRect(340, 20, 161, 21));
        REditETime = new QLineEdit(groupBox_21);
        REditETime->setObjectName(QString::fromUtf8("REditETime"));
        REditETime->setGeometry(QRect(90, 120, 141, 20));
        REditETime->setMaximumSize(QSize(16777215, 20));
        label_12 = new QLabel(groupBox_21);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(260, 20, 75, 20));
        label_14 = new QLabel(groupBox_21);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 70, 75, 20));
        label_15 = new QLabel(groupBox_21);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 20, 75, 20));
        label_16 = new QLabel(groupBox_21);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(9, 120, 75, 20));
        Rbtn_open = new QPushButton(groupBox_21);
        Rbtn_open->setObjectName(QString::fromUtf8("Rbtn_open"));
        Rbtn_open->setGeometry(QRect(280, 120, 71, 23));
        btn_modify = new QPushButton(groupBox_21);
        btn_modify->setObjectName(QString::fromUtf8("btn_modify"));
        btn_modify->setGeometry(QRect(430, 120, 61, 23));
        REditLibID_4 = new QLineEdit(groupBox_21);
        REditLibID_4->setObjectName(QString::fromUtf8("REditLibID_4"));
        REditLibID_4->setGeometry(QRect(340, 80, 161, 20));
        label_46 = new QLabel(groupBox_21);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(300, 50, 41, 21));
        label_46->setAlignment(Qt::AlignCenter);
        label_48 = new QLabel(groupBox_21);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(300, 80, 41, 21));
        label_48->setAlignment(Qt::AlignCenter);
        REditLibID_5 = new QLineEdit(groupBox_21);
        REditLibID_5->setObjectName(QString::fromUtf8("REditLibID_5"));
        REditLibID_5->setGeometry(QRect(340, 50, 161, 21));
        REditName_2 = new QLineEdit(groupBox_21);
        REditName_2->setObjectName(QString::fromUtf8("REditName_2"));
        REditName_2->setGeometry(QRect(91, 40, 141, 20));
        label_18 = new QLabel(groupBox_21);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 40, 75, 20));
        groupBox_41 = new QGroupBox(tab_2);
        groupBox_41->setObjectName(QString::fromUtf8("groupBox_41"));
        groupBox_41->setGeometry(QRect(10, 170, 511, 401));
        REditcode = new QLineEdit(groupBox_41);
        REditcode->setObjectName(QString::fromUtf8("REditcode"));
        REditcode->setGeometry(QRect(90, 20, 141, 20));
        label_26 = new QLabel(groupBox_41);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(9, 20, 75, 20));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(groupBox_41);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(0, 50, 91, 31));
        label_27->setAlignment(Qt::AlignCenter);
        label_27->setWordWrap(true);
        REditFacName = new QLineEdit(groupBox_41);
        REditFacName->setObjectName(QString::fromUtf8("REditFacName"));
        REditFacName->setGeometry(QRect(361, 60, 141, 20));
        label_28 = new QLabel(groupBox_41);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(250, 50, 111, 41));
        label_28->setAlignment(Qt::AlignCenter);
        label_28->setWordWrap(true);
        REditLibID = new QLineEdit(groupBox_41);
        REditLibID->setObjectName(QString::fromUtf8("REditLibID"));
        REditLibID->setGeometry(QRect(90, 90, 141, 20));
        label_29 = new QLabel(groupBox_41);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(9, 90, 75, 20));
        REditLibVersion = new QLineEdit(groupBox_41);
        REditLibVersion->setObjectName(QString::fromUtf8("REditLibVersion"));
        REditLibVersion->setGeometry(QRect(361, 90, 141, 20));
        label_30 = new QLabel(groupBox_41);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(250, 90, 111, 20));
        groupBox_5 = new QGroupBox(groupBox_41);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 120, 491, 271));
        label_35 = new QLabel(groupBox_5);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(20, 20, 30, 16));
        Rcm_data = new QComboBox(groupBox_5);
        Rcm_data->setObjectName(QString::fromUtf8("Rcm_data"));
        Rcm_data->setGeometry(QRect(56, 20, 69, 20));
        label_45 = new QLabel(groupBox_5);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(140, 20, 41, 21));
        label_45->setAlignment(Qt::AlignCenter);
        RListData = new QListWidget(groupBox_5);
        RListData->setObjectName(QString::fromUtf8("RListData"));
        RListData->setGeometry(QRect(10, 50, 471, 181));
        btn_add = new QPushButton(groupBox_5);
        btn_add->setObjectName(QString::fromUtf8("btn_add"));
        btn_add->setGeometry(QRect(400, 240, 71, 21));
        btn_delete = new QPushButton(groupBox_5);
        btn_delete->setObjectName(QString::fromUtf8("btn_delete"));
        btn_delete->setGeometry(QRect(326, 240, 71, 21));
        label_47 = new QLabel(groupBox_5);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(310, 20, 41, 21));
        label_47->setAlignment(Qt::AlignCenter);
        REditLibID_2 = new QLineEdit(groupBox_5);
        REditLibID_2->setObjectName(QString::fromUtf8("REditLibID_2"));
        REditLibID_2->setGeometry(QRect(180, 20, 111, 21));
        REditLibID_3 = new QLineEdit(groupBox_5);
        REditLibID_3->setObjectName(QString::fromUtf8("REditLibID_3"));
        REditLibID_3->setGeometry(QRect(350, 20, 111, 20));
        btn_modify_2 = new QPushButton(groupBox_5);
        btn_modify_2->setObjectName(QString::fromUtf8("btn_modify_2"));
        btn_modify_2->setGeometry(QRect(260, 240, 61, 23));
        comboBox = new QComboBox(groupBox_41);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(90, 50, 69, 22));
        cm_equipment = new QComboBox(groupBox_41);
        cm_equipment->setObjectName(QString::fromUtf8("cm_equipment"));
        cm_equipment->setGeometry(QRect(360, 10, 69, 22));
        label_31 = new QLabel(groupBox_41);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(270, 10, 75, 20));
        label_31->setAlignment(Qt::AlignCenter);
        btn_modify_3 = new QPushButton(groupBox_41);
        btn_modify_3->setObjectName(QString::fromUtf8("btn_modify_3"));
        btn_modify_3->setGeometry(QRect(430, 30, 81, 23));
        delete_equip = new QPushButton(groupBox_41);
        delete_equip->setObjectName(QString::fromUtf8("delete_equip"));
        delete_equip->setGeometry(QRect(350, 30, 81, 21));
        RTree = new QTreeWidget(tab_2);
        QTreeWidgetItem *__qtreewidgetitem1 = new QTreeWidgetItem();
        __qtreewidgetitem1->setText(0, QString::fromUtf8("1"));
        RTree->setHeaderItem(__qtreewidgetitem1);
        RTree->setObjectName(QString::fromUtf8("RTree"));
        RTree->setGeometry(QRect(530, 10, 371, 521));
        btn_zip_2 = new QPushButton(tab_2);
        btn_zip_2->setObjectName(QString::fromUtf8("btn_zip_2"));
        btn_zip_2->setGeometry(QRect(780, 550, 71, 21));
        tabwidgt->addTab(tab_2, QString());
        QtGuiApplicationClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(QtGuiApplicationClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 983, 23));
        QtGuiApplicationClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(QtGuiApplicationClass);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        QtGuiApplicationClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(QtGuiApplicationClass);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        QtGuiApplicationClass->setStatusBar(statusBar);

        retranslateUi(QtGuiApplicationClass);

        tabwidgt->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(QtGuiApplicationClass);
    } // setupUi

    void retranslateUi(QMainWindow *QtGuiApplicationClass)
    {
        QtGuiApplicationClass->setWindowTitle(QCoreApplication::translate("QtGuiApplicationClass", "QtGuiApplication", nullptr));
#if QT_CONFIG(tooltip)
        tabwidgt->setToolTip(QCoreApplication::translate("QtGuiApplicationClass", "<html><head/><body><p><br/></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
        btn_ok->setText(QCoreApplication::translate("QtGuiApplicationClass", "Ok", nullptr));
        groupBox->setTitle(QCoreApplication::translate("QtGuiApplicationClass", "Platforms", nullptr));
        label_38->setText(QCoreApplication::translate("QtGuiApplicationClass", "FlightName:", nullptr));
        label_39->setText(QCoreApplication::translate("QtGuiApplicationClass", "Code:", nullptr));
        label_40->setText(QCoreApplication::translate("QtGuiApplicationClass", "PlatformType:", nullptr));
        label_41->setText(QCoreApplication::translate("QtGuiApplicationClass", "PlatformRole:", nullptr));
        label_42->setText(QCoreApplication::translate("QtGuiApplicationClass", "MissionTask:", nullptr));
        label_43->setText(QCoreApplication::translate("QtGuiApplicationClass", "PlatformPlanId:", nullptr));
        label_44->setText(QCoreApplication::translate("QtGuiApplicationClass", "PlatformName:", nullptr));
        btn_create_3->setText(QCoreApplication::translate("QtGuiApplicationClass", "Add/Modify", nullptr));
        PLAT_DELETE->setText(QCoreApplication::translate("QtGuiApplicationClass", "Delete_Plat", nullptr));
        label_34->setText(QCoreApplication::translate("QtGuiApplicationClass", "type:", nullptr));
        data_3->setText(QCoreApplication::translate("QtGuiApplicationClass", "Add", nullptr));
        label_36->setText(QCoreApplication::translate("QtGuiApplicationClass", "category:", nullptr));
        label_37->setText(QCoreApplication::translate("QtGuiApplicationClass", "id:", nullptr));
        btn_create->setText(QCoreApplication::translate("QtGuiApplicationClass", "Modify", nullptr));
        label_17->setText(QCoreApplication::translate("QtGuiApplicationClass", "CurrentPlat", nullptr));
        pushButton->setText(QCoreApplication::translate("QtGuiApplicationClass", "Delete", nullptr));
        btn_zip->setText(QCoreApplication::translate("QtGuiApplicationClass", "Compress", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("QtGuiApplicationClass", "Mission", nullptr));
        label_4->setText(QCoreApplication::translate("QtGuiApplicationClass", "StartTime:", nullptr));
        label_5->setText(QCoreApplication::translate("QtGuiApplicationClass", "EndTime:", nullptr));
        label_6->setText(QCoreApplication::translate("QtGuiApplicationClass", "Description:", nullptr));
        label->setText(QCoreApplication::translate("QtGuiApplicationClass", "Code:", nullptr));
        btn_save->setText(QCoreApplication::translate("QtGuiApplicationClass", "SAVE", nullptr));
        label_3->setText(QCoreApplication::translate("QtGuiApplicationClass", "Ato:", nullptr));
        btn_create_2->setText(QCoreApplication::translate("QtGuiApplicationClass", "Modify", nullptr));
        label_7->setText(QCoreApplication::translate("QtGuiApplicationClass", "date", nullptr));
        label_8->setText(QCoreApplication::translate("QtGuiApplicationClass", "time", nullptr));
        btn_open->setText(QCoreApplication::translate("QtGuiApplicationClass", "OPEN", nullptr));
        label_2->setText(QCoreApplication::translate("QtGuiApplicationClass", "Name:", nullptr));
        tabwidgt->setTabText(tabwidgt->indexOf(tab), QCoreApplication::translate("QtGuiApplicationClass", "MDC", nullptr));
        groupBox_21->setTitle(QCoreApplication::translate("QtGuiApplicationClass", "Simulation", nullptr));
        Rbtn_new->setText(QCoreApplication::translate("QtGuiApplicationClass", "New", nullptr));
        label_9->setText(QCoreApplication::translate("QtGuiApplicationClass", "StartTime:", nullptr));
        label_12->setText(QCoreApplication::translate("QtGuiApplicationClass", "Description:", nullptr));
        label_14->setText(QCoreApplication::translate("QtGuiApplicationClass", "Operator:", nullptr));
        label_15->setText(QCoreApplication::translate("QtGuiApplicationClass", "Code:", nullptr));
        label_16->setText(QCoreApplication::translate("QtGuiApplicationClass", "EndTime:", nullptr));
        Rbtn_open->setText(QCoreApplication::translate("QtGuiApplicationClass", "Open", nullptr));
        btn_modify->setText(QCoreApplication::translate("QtGuiApplicationClass", "Modify", nullptr));
        label_46->setText(QCoreApplication::translate("QtGuiApplicationClass", "Date:", nullptr));
        label_48->setText(QCoreApplication::translate("QtGuiApplicationClass", "Time:", nullptr));
        label_18->setText(QCoreApplication::translate("QtGuiApplicationClass", "Name:", nullptr));
        groupBox_41->setTitle(QCoreApplication::translate("QtGuiApplicationClass", "Equipment", nullptr));
        label_26->setText(QCoreApplication::translate("QtGuiApplicationClass", "Code:", nullptr));
        label_27->setText(QCoreApplication::translate("QtGuiApplicationClass", "Equipment Lab ID:", nullptr));
        label_28->setText(QCoreApplication::translate("QtGuiApplicationClass", "Equipment Factory Name:", nullptr));
        label_29->setText(QCoreApplication::translate("QtGuiApplicationClass", "EwlibraryID:", nullptr));
        label_30->setText(QCoreApplication::translate("QtGuiApplicationClass", "EwLibraryVersion:", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("QtGuiApplicationClass", "Recorded Data", nullptr));
        label_35->setText(QCoreApplication::translate("QtGuiApplicationClass", "Type:", nullptr));
        label_45->setText(QCoreApplication::translate("QtGuiApplicationClass", "Date:", nullptr));
        btn_add->setText(QCoreApplication::translate("QtGuiApplicationClass", "Add", nullptr));
        btn_delete->setText(QCoreApplication::translate("QtGuiApplicationClass", "Delete", nullptr));
        label_47->setText(QCoreApplication::translate("QtGuiApplicationClass", "Time:", nullptr));
        btn_modify_2->setText(QCoreApplication::translate("QtGuiApplicationClass", "Modify", nullptr));
        label_31->setText(QCoreApplication::translate("QtGuiApplicationClass", "Equipments:", nullptr));
        btn_modify_3->setText(QCoreApplication::translate("QtGuiApplicationClass", "Add/Modify", nullptr));
        delete_equip->setText(QCoreApplication::translate("QtGuiApplicationClass", "Delete_Equip", nullptr));
        btn_zip_2->setText(QCoreApplication::translate("QtGuiApplicationClass", "Compress", nullptr));
        tabwidgt->setTabText(tabwidgt->indexOf(tab_2), QCoreApplication::translate("QtGuiApplicationClass", "RDC", nullptr));
    } // retranslateUi

};

namespace Ui {
    class QtGuiApplicationClass: public Ui_QtGuiApplicationClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QTGUIAPPLICATION_H
